.PHONY: build test lint clean assemble help openapi-generate openapi-check

CONTRACTS_ROOT ?= $(shell cd .. && pwd)/octomil-contracts
OPENAPI_GEN_SCRIPT := $(CONTRACTS_ROOT)/tools/sdkgen/generate-kotlin.sh

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

build: ## Build all modules
	./gradlew build

test: ## Run unit tests
	./gradlew test

lint: ## Run lint checks
	./gradlew lint ktlintCheck

format: ## Format code with ktlint
	./gradlew ktlintFormat

assemble: ## Assemble release AAR
	./gradlew :octomil:assembleRelease

clean: ## Clean build artifacts
	./gradlew clean

openapi-generate: ## Regenerate Kotlin transport client from octomil-contracts OpenAPI spec
	OCTOMIL_ANDROID_PATH=$(PWD) OCTOMIL_ANDROID=1 $(OPENAPI_GEN_SCRIPT)

openapi-check: ## Verify generated transport files exist and carry the correct AUTOGENERATED banner
	@bash scripts/check_openapi_banner.sh
