package ai.octomil.chat

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A message in a chat conversation, mirroring the OpenAI Chat Completions API.
 *
 * ```kotlin
 * val messages = listOf(
 *     ChatMessage.system("You are a helpful assistant."),
 *     ChatMessage.user("What is machine learning?"),
 * )
 * ```
 */
@Serializable
data class ChatMessage(
    /** The role of the message author. */
    val role: Role,
    /** The text content of the message. Null when the assistant uses tool calls. */
    val content: String? = null,
    /** An optional name for the participant (used with tool role). */
    val name: String? = null,
    /** Tool calls generated by the model. Only present on assistant messages. */
    @SerialName("tool_calls")
    val toolCalls: List<ToolCall>? = null,
    /** The ID of the tool call this message is a response to. Only for tool role. */
    @SerialName("tool_call_id")
    val toolCallId: String? = null,
) {
    @Serializable
    enum class Role {
        @SerialName("system") SYSTEM,
        @SerialName("user") USER,
        @SerialName("assistant") ASSISTANT,
        @SerialName("tool") TOOL,
    }

    companion object {
        fun system(content: String) = ChatMessage(role = Role.SYSTEM, content = content)
        fun user(content: String) = ChatMessage(role = Role.USER, content = content)
        fun assistant(content: String) = ChatMessage(role = Role.ASSISTANT, content = content)
        fun tool(content: String, toolCallId: String) =
            ChatMessage(role = Role.TOOL, content = content, toolCallId = toolCallId)
    }
}
