package ai.octomil.chat

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 * A tool the model may call, mirroring the OpenAI tool format.
 *
 * ```kotlin
 * val tool = Tool.function(
 *     name = "get_weather",
 *     description = "Get the current weather for a location",
 *     parameters = buildJsonObject {
 *         put("type", JsonPrimitive("object"))
 *         putJsonObject("properties") {
 *             putJsonObject("location") {
 *                 put("type", JsonPrimitive("string"))
 *             }
 *         }
 *     },
 * )
 * ```
 */
@Serializable
data class Tool(
    /** The type of tool. Currently only "function" is supported. */
    val type: String = "function",
    /** The function definition. */
    val function: FunctionDef,
) {
    companion object {
        fun function(
            name: String,
            description: String,
            parameters: JsonObject? = null,
        ) = Tool(
            type = "function",
            function = FunctionDef(
                name = name,
                description = description,
                parameters = parameters,
            ),
        )
    }
}

/**
 * A function definition within a tool.
 */
@Serializable
data class FunctionDef(
    /** The name of the function. */
    val name: String,
    /** A description of what the function does. */
    val description: String,
    /** JSON Schema describing the function's parameters. */
    val parameters: JsonObject? = null,
)

/**
 * A tool call generated by the model (OpenAI wire format).
 *
 * This is the legacy representation used for Chat Completions API compatibility.
 * For the canonical domain-level tool call, see [DomainToolCall].
 */
@Serializable
data class LegacyToolCall(
    /** The ID of the tool call. */
    val id: String,
    /** The type of tool call. Currently only "function". */
    val type: String = "function",
    /** The function call details. */
    val function: FunctionCall,
)

/**
 * A function call with name and serialized arguments.
 */
@Serializable
data class FunctionCall(
    /** The name of the function to call. */
    val name: String,
    /** The arguments as a JSON string. */
    val arguments: String,
)
