package ai.octomil.conformance

// Shared Kotlin conformance support types.
// Generated by scripts/generate_conformance.py (target=kotlin).
// Shared across all CapabilityLifecycleConformanceTest_*.kt files.
enum class Quantifier { EXACTLY_ONE, ONE_OR_MORE, ZERO_OR_MORE }
data class EventStep(val eventName: String, val quantifier: Quantifier)
