#!/usr/bin/env bash
# Verify that the generated transport directory exists and every .kt file
# carries the AUTOGENERATED banner reporting openapi-generator-cli==7.10.0.
#
# Usage: bash scripts/check_openapi_banner.sh
# Exit:  0 on success, non-zero on any failure.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TRANSPORT_DIR="$REPO_ROOT/octomil/src/main/kotlin/ai/octomil/generated/transport"
EXPECTED_VERSION="7.10.0"
EXPECTED_BANNER="// Generator:  openapi-generator-cli==${EXPECTED_VERSION} (jvm-okhttp4)"

# ── Check directory exists ────────────────────────────────────────────────────
if [ ! -d "$TRANSPORT_DIR" ]; then
    echo "ERROR: generated/transport directory missing: $TRANSPORT_DIR" >&2
    echo "Run: make openapi-generate" >&2
    exit 1
fi

# ── Count files ───────────────────────────────────────────────────────────────
FILE_COUNT=$(find "$TRANSPORT_DIR" -name "*.kt" | wc -l | tr -d ' ')
if [ "$FILE_COUNT" -eq 0 ]; then
    echo "ERROR: no .kt files found in $TRANSPORT_DIR" >&2
    exit 1
fi
echo "→ Found $FILE_COUNT .kt files in generated/transport/"

# ── Check first file banner ───────────────────────────────────────────────────
# Collect the file list ONCE. Avoid `find | sort | head -1`: under
# `set -o pipefail`, head closes the pipe after one line and sort dies with
# SIGPIPE ("write error", exit 2), aborting the whole script — which only
# manifests once the dir is large enough (490 files) for sort to still be
# writing when head exits. Pure-bash first-line extraction sidesteps it.
ALL_FILES=$(find "$TRANSPORT_DIR" -name "*.kt" | sort)
FIRST_FILE=${ALL_FILES%%$'\n'*}
if ! grep -qF "$EXPECTED_BANNER" "$FIRST_FILE"; then
    echo "ERROR: banner mismatch in $FIRST_FILE" >&2
    echo "  Expected to find: $EXPECTED_BANNER" >&2
    echo "  Actual header:" >&2
    head -5 "$FIRST_FILE" >&2
    echo "" >&2
    echo "Run: make openapi-generate  (requires openapi-generator-cli==${EXPECTED_VERSION})" >&2
    exit 1
fi

# ── Spot-check a sample of files for the banner ──────────────────────────────
MISMATCH_COUNT=0
while IFS= read -r f; do
    if ! grep -qF "$EXPECTED_BANNER" "$f"; then
        echo "WARN: banner missing in $f" >&2
        MISMATCH_COUNT=$((MISMATCH_COUNT + 1))
    fi
done <<< "$ALL_FILES"

if [ "$MISMATCH_COUNT" -gt 0 ]; then
    echo "ERROR: $MISMATCH_COUNT file(s) missing the expected banner." >&2
    exit 1
fi

echo "OK: all $FILE_COUNT generated files carry openapi-generator-cli==${EXPECTED_VERSION} banner."
