package ai.edgeml.pairing

import android.content.Intent
import android.net.Uri
import timber.log.Timber

/**
 * Handles deep links for the EdgeML SDK.
 *
 * The `edgeml://` custom URL scheme allows consuming apps to open directly to
 * the pairing screen when a user scans a QR code generated by `edgeml deploy --phone`.
 *
 * ## Supported deep link format
 *
 * ```
 * edgeml://pair?token=<pairing-code>&host=<server-url>
 * ```
 *
 * - **token** (required): The pairing code that identifies the session.
 * - **host** (optional): The EdgeML server URL. Defaults to `https://api.edgeml.ai`
 *   when omitted.
 *
 * ## Integration
 *
 * Consuming apps must register an intent filter in their `AndroidManifest.xml`:
 *
 * ```xml
 * <activity android:name=".YourPairingActivity">
 *     <intent-filter>
 *         <action android:name="android.intent.action.VIEW" />
 *         <category android:name="android.intent.category.DEFAULT" />
 *         <category android:name="android.intent.category.BROWSABLE" />
 *         <data android:scheme="edgeml" android:host="pair" />
 *     </intent-filter>
 * </activity>
 * ```
 *
 * Then handle the intent in the activity:
 *
 * ```kotlin
 * override fun onCreate(savedInstanceState: Bundle?) {
 *     super.onCreate(savedInstanceState)
 *
 *     val action = DeepLinkHandler.handleIntent(intent)
 *     when (action) {
 *         is DeepLinkHandler.DeepLinkAction.Pair -> {
 *             // Start pairing flow with action.token and action.host
 *         }
 *         is DeepLinkHandler.DeepLinkAction.Unknown -> {
 *             // Unrecognized deep link
 *         }
 *         null -> {
 *             // Not a deep link intent
 *         }
 *     }
 * }
 * ```
 */
object DeepLinkHandler {

    /** The custom URL scheme used by EdgeML deep links. */
    const val SCHEME = "edgeml"

    /** The default EdgeML server URL used when the deep link omits the host parameter. */
    const val DEFAULT_HOST = "https://api.edgeml.ai"

    /**
     * Actions that can be parsed from an `edgeml://` deep link.
     */
    sealed class DeepLinkAction {
        /**
         * A pairing action initiated by scanning a QR code from `edgeml deploy --phone`.
         *
         * @param token The pairing code that identifies the session on the server.
         * @param host The EdgeML server URL, or [DEFAULT_HOST] if not specified in the link.
         */
        data class Pair(val token: String, val host: String) : DeepLinkAction()

        /**
         * An unrecognized `edgeml://` deep link.
         *
         * The consuming app may choose to log this or display a generic error.
         *
         * @param uri The original URI that could not be mapped to a known action.
         */
        data class Unknown(val uri: Uri) : DeepLinkAction()
    }

    /**
     * Parse an incoming [Uri] into a [DeepLinkAction].
     *
     * Returns `null` if the URI does not use the `edgeml` scheme. Returns
     * [DeepLinkAction.Unknown] if the scheme matches but the action (host) is
     * not recognized. Returns [DeepLinkAction.Pair] for a valid pairing link.
     *
     * A valid pairing URI looks like:
     * ```
     * edgeml://pair?token=ABC123&host=https://api.edgeml.ai
     * ```
     *
     * The `token` query parameter is required. If missing, this returns `null`
     * because there is no valid pairing session to connect to.
     *
     * @param uri The URI to parse.
     * @return A [DeepLinkAction], or `null` if the URI is not an EdgeML deep link
     *   or is missing required parameters.
     */
    fun parse(uri: Uri): DeepLinkAction? {
        if (uri.scheme != SCHEME) {
            Timber.d("Ignoring URI with non-EdgeML scheme: %s", uri.scheme)
            return null
        }

        return when (uri.host) {
            "pair" -> {
                val token = uri.getQueryParameter("token")
                if (token.isNullOrBlank()) {
                    Timber.w("Pairing deep link missing required 'token' parameter: %s", uri)
                    return null
                }
                val host = uri.getQueryParameter("host")?.takeIf { it.isNotBlank() }
                    ?: DEFAULT_HOST
                Timber.i("Parsed pairing deep link: token=%s host=%s", token, host)
                DeepLinkAction.Pair(token = token, host = host)
            }
            else -> {
                Timber.w("Unknown EdgeML deep link action: %s", uri.host)
                DeepLinkAction.Unknown(uri)
            }
        }
    }

    /**
     * Extract and parse a deep link from an [Intent].
     *
     * Convenience method for use in `Activity.onCreate()` or `Activity.onNewIntent()`.
     * Extracts the data URI from the intent and delegates to [parse].
     *
     * @param intent The incoming intent, typically from `getIntent()` or `onNewIntent()`.
     * @return A [DeepLinkAction], or `null` if the intent has no data URI or the URI
     *   is not a valid EdgeML deep link.
     */
    fun handleIntent(intent: Intent): DeepLinkAction? {
        val uri = intent.data ?: return null
        return parse(uri)
    }

    /**
     * The XML snippet that consuming apps should add to their `AndroidManifest.xml`
     * inside the activity that handles pairing.
     *
     * Provided as a constant for documentation and tooling purposes.
     */
    const val MANIFEST_INTENT_FILTER = """
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data android:scheme="edgeml" android:host="pair" />
        </intent-filter>"""
}
